# Generated by Django 2.1.4 on 2019-03-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_booked_viewings_contact_on_property_listings_waiting_list_listrequest_propety_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked_viewings',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='booked_viewings',
            name='email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
