# Generated by Django 2.1.4 on 2019-03-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190319_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_on_property',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
