# Generated by Django 2.1.4 on 2019-03-21 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_on_property_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='paypal_payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField(blank=True)),
                ('transaction_status', models.CharField(blank=True, max_length=800)),
                ('transaction_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
