# Generated by Django 2.1.4 on 2019-03-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_paypal_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='propety',
            name='tour',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
