# Generated by Django 2.1.4 on 2019-03-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_propety_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypal_payments',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
