# Generated by Django 2.1.4 on 2019-03-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190323_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='listrequest',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
